---

- name: Manage httpd.conf
  hosts: web
  become: true
  tasks:
  - name: Copy Apache Configs
    copy:
      src: httpd.conf
      dest: /etc/httpd/conf/
    notify:
      - restart_apache

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted