---

- name: Fill motd file
  hosts: node1
  become: true
  tasks:
    - name: motd template
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
